name: Enviar arquivo sensível para instância do GCE
on:
  push:
    branches:
      - main
jobs:
  enviar-arquivo:
    runs-on: ubuntu-latest
    steps:
    - name: Enviar arquivo para instância do GCE
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        credentials: ${{ secrets.GCP_SA_KEY }}
        # substitua [NOME_INSTANCIA] pelo nome da sua instância do GCE
        # substitua [CAMINHO_DESTINO] pelo caminho da pasta onde deseja enviar o arquivo
        args: ['compute', 'scp', '${{ secrets.NOME_ARQUIVO_SENSIVEL }}', '[NOME_INSTANCIA]:[CAMINHO_DESTINO]']
      env:
        # configure as variáveis de ambiente para autenticação com o GCP
        # substitua [NOME_SA_KEY] pelo nome da sua Secret do GitHub contendo a chave de serviço do GCP
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/${{ secrets.NOME_SA_KEY }}
