name: Deploy

on:
  push:
    branches:
      - main
      - js/add-docker-airflow

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v2

      - name: Sync
        uses: patrickwyler/gcs-bucket-sync-action@1.3
        with:
          secrets: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          bucket: 'dataflow_jose'
          exclude: '.*\.md$|\.gitignore$|\.git/.*$|\.github/.*$'
